menu:
  Home: /
  Archives: /archives

widgets:
- search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username: alebelcor
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid: ra-51a2a190502ebfe9
  facebook: true
  twitter: true
  google: true
  pinterest: false

fancybox: false

google_analytics: UA-39910763-1
rss:
